# Generated by Django 4.0.4 on 2022-04-14 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobreviventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('fem', 'fem'), ('masc', 'masc')], max_length=4)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('strike', models.IntegerField(default=0)),
                ('infectado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.IntegerField()),
                ('alimentacao', models.IntegerField()),
                ('medicacao', models.IntegerField()),
                ('municao', models.IntegerField()),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='api.sobreviventes')),
            ],
        ),
    ]
