# Generated by Django 4.0.4 on 2022-04-14 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sobreviventes_idade_alter_inventario_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.sobreviventes'),
        ),
    ]
