# Generated by Django 4.0.4 on 2022-04-14 15:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inventario_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='agua',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='alimentacao',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='medicacao',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='municao',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='sobreviventes',
            name='idade',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
    ]
