# Generated by Django 4.0.4 on 2022-04-14 17:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sobreviventes_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobreviventes',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sobreviventes',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
