# Generated by Django 4.0.4 on 2022-04-14 18:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_inventario_agua_alter_inventario_alimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='agua',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='alimentacao',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='medicacao',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='municao',
            field=models.IntegerField(default=0, validators=[api.models.maior_que_zero]),
        ),
    ]
