# Generated by Django 4.0.4 on 2022-04-14 18:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_inventario_agua_alter_inventario_alimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobreviventes',
            name='latitude',
            field=models.FloatField(validators=[api.validators.valida_latitude]),
        ),
        migrations.AlterField(
            model_name='sobreviventes',
            name='longitude',
            field=models.FloatField(validators=[api.validators.valida_longitude]),
        ),
    ]
