# Generated by Django 4.0.4 on 2022-04-16 19:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_denuncia_doente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='agua',
            field=models.FloatField(default=0, validators=[api.validators.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='alimentacao',
            field=models.FloatField(default=0, validators=[api.validators.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='medicacao',
            field=models.FloatField(default=0, validators=[api.validators.maior_que_zero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='municao',
            field=models.FloatField(default=0, validators=[api.validators.maior_que_zero]),
        ),
    ]
